### PR TITLE
support laravel 6

### PR DESCRIPTION
**Pull request by okaufmann**
Tests green

### CODE REVIEW

**Comment by kronthto** [comment]
Thanks, I didn't get the news yet about the L6 release 😄. And also the testbench is already up to date 💯.

Will test/merge this probably at the weekend / check the changelog for breaking stuff.

Gonna check why Travis isn't showing in GitHub / how I migrate it to GitHub apps. 
The build had some failures on old versions due to Testbench interface changes (was planning on removing that from the build matrix anyways) and didn't include L6: https://travis-ci.org/kronthto/laravel-oauth2-login/builds/586243219
Can you maybe adjust the build matrix similar to this to include it : https://github.com/kronthto/laravel-oauth2-login/commit/17854400be94ece4336b0ba61024b47a82bbdf9e#diff-354f30a63fb0907d4ad57269548329e3

Edit/Update: Sorry, other things came up, but I have this on my list / didn't forget about it.

**Comment by okaufmann** [comment]
I did update the test matrix. 

How should it be configured to run tests with laravel 6 only with php 7.2 and up? Laravel 6 does require php 7.2 and up only...

**Comment by kronthto** [comment]
Travis magically just works again / reports the status 🤔

I will push some things to your branch / the adjustments to the build matrix and then test it.

Also decided to drop support for L5.4 / PHP 5.6 in the next release (those can still require the current [1.8.0 version](https://github.com/kronthto/laravel-oauth2-login/releases/tag/v1.8.0).

**Comment by kronthto** [comment]
All good, tested in a local fresh installation. Released in 1.9.0

**Pull request merged**
