### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by subtronic**
Add compatibility for Laravel 5.7

### CODE REVIEW

**Comment by kronthto** [comment]
I also worked on this for a bit, the test assuring that `url.intended` is set when redirecting is currently failing with L5.7: https://travis-ci.org/kronthto/laravel-oauth2-login/builds/448511404

I dug in quite deep, but couldn't find a reason/solution. The Request object doesn't get a RouteResolver instance for whatever reason. Gotta take another look at this soon...

**Comment by subtronic** [comment]
At first glance, it wants to check whether routes are being created in the test case.
I quickly looked on request test orchestral/testbench, and in the test [they don't coverage method get(), they use call()](https://github.com/orchestral/testbench-core/blob/e1ac94850d3f81d27e4cc99b8645485b66dad80f/tests/RouteTest.php#L43) and they set route with using [prefix notation](https://github.com/orchestral/testbench-core/blob/e1ac94850d3f81d27e4cc99b8645485b66dad80f/tests/RouteTest.php#L27) 
I'll try to look deeper at the weekend.

**Comment by kronthto** [comment]
I will also try to setup a real Laravel 5.7 project and check whether it "remembers" the intended URL. If it does and it's just an issue in the orchestral/testbench, we can IMO still merge this.

**Comment by kronthto** [comment]
Works in a real project.

**Comment by kronthto** [comment]
I found the issue / was able to solve it in ace3a5f0b2522f47b139ea24e801e3af736a1dde.

Thanks to https://stackoverflow.com/a/31868954/7362396 I noticed that I assigned the Middleware as a global middleware in the kernel instead of route-middleware, like it should be. The Readme also says it should be added to "routes". So no issue in Testbench :)

Actually I'm not sure how this worked in L5.6, anyways, I think the test is better now and passes.

**Comment by kronthto** [comment]
Released in [v1.5.0](https://github.com/kronthto/laravel-oauth2-login/releases/tag/v1.5.0)

**Comment by subtronic** [comment]
I tried do more test for Testbench, and they all passed :)
Thank you for you work!

**Pull request merged**
