### PR TITLE
laravel 7 support

### PR DESCRIPTION
**Pull request by madagon**

### CODE REVIEW

**Comment by MrPalamen** [comment]
+1

**Comment by madagon** [comment]
I don't know about Travis. Could someone assist, please?

**Comment by kronthto** [comment]
The Travis error is just PHP7.1 in the build matrix conflicting with Laravel 7, I'll fix that. Probably will get to making a quick test and merging this tomorrow, sorry for the delay.

**Comment by kronthto** [comment]
tbh can't explain why one errors (some clone timeout). But all green in the other so that is fine. 
Maybe I should give GitHub actions a try at some point .. 😸 

Tested it also in a simple Laravel 7 installation and it works, so merged & released a new version.

**Comment by madagon** [comment]
> tbh can't explain why one errors (some clone timeout). But all green in the other so that is fine.
> Maybe I should give GitHub actions a try at some point .. 
> 
> Tested it also in a simple Laravel 7 installation and it works, so merged & released a new version.

Strange! Thank you. :)

**Pull request merged**
